# Title : Personalized Medical Recommendation System with Machine Learning
# Description:
welcome to our cutting-edge personalized Medical Recommendation System, a powerful platform designrd to assist users in understanding and managing their 
health leveraging the capabilities of machine learning. Our system analyzes user-input symptomps to product potential diseases accurately

# load dataset & tools

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv(r"C:\Users\Administrator\Downloads\archive (1)\Training.csv")

In [4]:
dataset.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [5]:
dataset.shape

(4920, 133)

In [6]:
dataset['prognosis'].unique()

<ArrowStringArray>
[                       'Fungal infection',
                                 'Allergy',
                                    'GERD',
                     'Chronic cholestasis',
                           'Drug Reaction',
                     'Peptic ulcer diseae',
                                    'AIDS',
                               'Diabetes ',
                         'Gastroenteritis',
                        'Bronchial Asthma',
                           'Hypertension ',
                                'Migraine',
                    'Cervical spondylosis',
            'Paralysis (brain hemorrhage)',
                                'Jaundice',
                                 'Malaria',
                             'Chicken pox',
                                  'Dengue',
                                 'Typhoid',
                             'hepatitis A',
                             'Hepatitis B',
                             'Hepatitis C',
                             'Hepatitis D',
                             'Hepatitis E',
                     'Alcoholic hepatitis',
                            'Tuberculosis',
                             'Common Cold',
                               'Pneumonia',
            'Dimorphic hemmorhoids(piles)',
                            'Heart attack',
                          'Varicose veins',
                          'Hypothyroidism',
                         'Hyperthyroidism',
                            'Hypoglycemia',
                         'Osteoarthristis',
                               'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
                                    'Acne',
                 'Urinary tract infection',
                               'Psoriasis',
                                'Impetigo']
Length: 41, dtype: str

# Train Test Split

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [8]:
x = dataset.drop("prognosis", axis = 1)
y = dataset['prognosis']

In [9]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [10]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: str

In [11]:
Y

array([15, 15, 15, ..., 38, 35, 27], shape=(4920,))

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,Y, test_size=0.3, random_state=20)

In [13]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

# Training Top Models

In [14]:
!pip install SVC

Requirement already satisfied: SVC in c:\users\administrator\anaconda3\lib\site-packages (0.1)
Requirement already satisfied: xlrd>=0.9.3 in c:\users\administrator\anaconda3\lib\site-packages (from SVC) (2.0.2)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Administrator\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Administrator\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Administrator\anaconda3\Lib\site-packages)

In [15]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
# create a dictionary to store model
models = {
    "SVC":SVC(kernel = 'linear'),
    "RandomForest":RandomForestClassifier(n_estimators=100,random_state=42),
    "GrandientBoosting":GradientBoostingClassifier(n_estimators=100,random_state=42),
    "KNeighbors":KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB":MultinomialNB()             
}
for model_name, model in models.items():
       # train model
    model.fit(x_train,y_train)
    # test model
    predictions=model.predict(x_test)
    # calculate accuracy
    accuracy = accuracy_score(y_test,predictions)
    # calculate confusion matrix
    cm=confusion_matrix(y_test,predictions)
    print(f"{model_name} accuracy:{accuracy}")
    print(f"{model_name} Confusion Matrix:")
    print(np.array2string(cm, separator= ','))

SVC accuracy:1.0
SVC Confusion Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
RandomForest accuracy:1.0
RandomForest Confusion Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
GrandientBoosting accuracy:1.0
GrandientBoosting Confusion Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
KNeighbors accuracy:1.0
KNeighbors Confusion Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
MultinomialNB accuracy:1.0
MultinomialNB Confusion Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]

# Single Prediction

In [16]:
svc = SVC(kernel='linear')
svc.fit(x_train,y_train)
ypred=svc.predict(x_test)
accuracy_score(y_test,ypred)

1.0

In [17]:
# saving model
import pickle

In [18]:
# load model
svc = pickle.load(open(r'C:\Users\Administrator\Downloads\svc (1).pkl','rb'))

C:\Users\Administrator\anaconda3\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 1.3.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [19]:
# test 1
print("Predicted level:",svc.predict(x_test.iloc[0].values.reshape(1,-1)))
print("Actual level:", y_test[0])

Predicted level: [40]
Actual level: 40

C:\Users\Administrator\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [20]:
# test 2
print("Predicted level:",svc.predict(x_test.iloc[10].values.reshape(1,-1)))
print("Actual level:", y_test[10])

Predicted level: [20]
Actual level: 20

C:\Users\Administrator\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

# Recommendation system and Prediction
# Load database and use logic for recommendation

In [21]:
sym_des = pd.read_csv(r'C:\Users\Administrator\Downloads\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main (1)\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main\symtoms_df.csv')
precautions = pd.read_csv(r'C:\Users\Administrator\Downloads\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main (1)\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main\precautions_df.csv')
workout = pd.read_csv(r'C:\Users\Administrator\Downloads\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main (1)\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main\workout_df.csv')
description = pd.read_csv(r'C:\Users\Administrator\Downloads\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main (1)\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main\description.csv')
medications = pd.read_csv(r'C:\Users\Administrator\Downloads\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main (1)\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main\medications.csv')
diets = pd.read_csv(r'C:\Users\Administrator\Downloads\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main (1)\Medicine-Recommendation-System-Personalized-Medical-Recommendation-System-with-Machine-Learning-main\diets.csv')

In [22]:
diets

,Disease,Diet
0,Fungal infection,"['Antifungal Diet', 'Probiotics', 'Garlic', 'C..."
1,Allergy,"['Elimination Diet', 'Omega-3-rich foods', 'Vi..."
2,GERD,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
3,Chronic cholestasis,"['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot..."
4,Drug Reaction,"['Antihistamine Diet', 'Omega-3-rich foods', '..."
5,Peptic ulcer disease,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
6,AIDS,"['Balanced Diet', 'Protein-rich foods', 'Fruit..."
7,Diabetes,"['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea..."
8,Gastroenteritis,"['Bland Diet', 'Bananas', 'Rice', 'Applesauce'..."
9,Bronchial Asthma,"['Anti-Inflammatory Diet', 'Omega-3-rich foods..."
10,Hypertension,"['DASH Diet', 'Low-sodium foods', 'Fruits and ..."
11,Migraine,"['Migraine Diet', 'Low-Tyramine Diet', 'Caffei..."
12,Cervical spondylosis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
13,Paralysis (brain hemorrhage),"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
14,Jaundice,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
15,Malaria,"['Malaria Diet', 'Hydration', 'High-Calorie Di..."
16,Chicken pox,"['Chicken Pox Diet', 'High-Calorie Diet', 'Sof..."
17,Dengue,"['Dengue Diet', 'Hydration', 'High-Calorie Die..."
18,Typhoid,"['Typhoid Diet', 'High-Calorie Diet', 'Soft an..."
19,hepatitis A,"['Hepatitis A Diet', 'High-Calorie Diet', 'Sof..."
20,Hepatitis B,"['Hepatitis B Diet', 'High-Calorie Diet', 'Sof..."
21,Hepatitis C,"['Hepatitis C Diet', 'High-Calorie Diet', 'Sof..."
22,Hepatitis D,"['Hepatitis D Diet', 'High-Calorie Diet', 'Sof..."
23,Hepatitis E,"['Hepatitis E Diet', 'High-Calorie Diet', 'Sof..."
24,Alcoholic hepatitis,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
25,Tuberculosis,"['TB Diet', 'High-Calorie Diet', 'Soft and bla..."
26,Common Cold,"['Cold Diet', 'Hydration', 'Warm fluids', 'Res..."
27,Pneumonia,"['Pneumonia Diet', 'High-Calorie Diet', 'Soft ..."
28,Dimorphic hemmorhoids(piles),"['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra..."
29,Heart attack,"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
30,Varicose veins,"['Varicose Veins Diet', 'High-Fiber Diet', 'Fr..."
31,Hypothyroidism,"['Hypothyroidism Diet', 'Iodine-rich foods', '..."
32,Hyperthyroidism,"['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C..."
33,Hypoglycemia,"['Hypoglycemia Diet', 'Complex carbohydrates',..."
34,Osteoarthristis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
35,Arthritis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
36,(vertigo) Paroymsal Positional Vertigo,"['Vertigo Diet', 'Low-Salt Diet', 'Hydration',..."
37,Acne,"['Acne Diet', 'Low-Glycemic Diet', 'Hydration'..."
38,Urinary tract infection,"['UTI Diet', 'Hydration', 'Cranberry juice', '..."
39,Psoriasis,"['Psoriasis Diet', 'Anti-Inflammatory Diet', '..."
40,Impetigo,"['Impetigo Diet', 'Antibiotic treatment', 'Fru..."

In [23]:
def helper(dis):
    desc = description[description['Disease'] == predicted_disease]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']


    return desc,pre,med,die,wrkout

symptoms_dict = {'itching': 0, '': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

# Model Prediction function
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]

In [25]:
# test 1:
symptoms = input("Enter your symptoms.......")
user_symptoms = [s.strip() for s in symptoms.split(',')]
user_symptoms = [symptom.strip("[]' ") for symptom in user_symptoms]
predicted_disease = get_predicted_value(user_symptoms)
desc, pre, med, die, wrkout = helper(predicted_disease)
print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1
print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1
print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1
print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter your symptoms....... itching

=================predicted disease============
Fungal infection
=================description==================
Fungal infection is a common skin condition caused by fungi.
=================precautions==================
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths
=================medications==================
5 :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
=================workout==================
6 :  Avoid sugary foods
7 :  Consume probiotics
8 :  Increase intake of garlic
9 :  Include yogurt in diet
10 :  Limit processed foods
11 :  Stay hydrated
12 :  Consume green tea
13 :  Eat foods rich in zinc
14 :  Include turmeric in diet
15 :  Eat fruits and vegetables
=================diets==================
16 :  ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']

C:\Users\Administrator\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [ ]:
print(predicted_disease)
print(desc)
print(pre)

In [27]:
# Test 1
# Split the user's input into a list of symptoms (assuming they are comma-separated) # yellow_crust_ooze,red_sore_around_nose,small_dents_in_nails,inflammatory_nails,blister
symptoms = input("Enter your symptoms.......")
user_symptoms = [s.strip() for s in symptoms.split(',')]
# Remove any extra characters, if any
user_symptoms = [symptom.strip("[]' ") for symptom in user_symptoms]
predicted_disease = get_predicted_value(user_symptoms)

desc, pre, med, die, wrkout = helper(predicted_disease)

print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter your symptoms....... nodal_skin_eruptions

=================predicted disease============
Fungal infection
=================description==================
Fungal infection is a common skin condition caused by fungi.
=================precautions==================
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths
=================medications==================
5 :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
=================workout==================
6 :  Avoid sugary foods
7 :  Consume probiotics
8 :  Increase intake of garlic
9 :  Include yogurt in diet
10 :  Limit processed foods
11 :  Stay hydrated
12 :  Consume green tea
13 :  Eat foods rich in zinc
14 :  Include turmeric in diet
15 :  Eat fruits and vegetables
=================diets==================
16 :  ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']

C:\Users\Administrator\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [ ]:
# let's use pycharm flask app
# but install this version in pycharm
import sklearn
print(sklearn.__version__)